### ISSUE TITLE
Any chance in getting this bumped to 5.2?

### ISSUE THREAD

**Issue by skattabrain** [mixdinternet/galleries#1]
Thank you

**Comment by jleonardolemos** [comment]
The Admix is developed over Laravel LTS version, so the packages for him too.
You can download the Mixdinternet\Galleries as a zip file and autoload him in composer.json file at  psr-4 Key, you will need to install all dependencies manually too.
If any dependency needs to Laravel LTS you can do the same thing with him.
Dont forgget to run composer dumpautoload.

That is a composer.json sample. That is working!
https://gist.github.com/jleonardolemos/892c1ac925fc09b42e663b2f1702e516

**Comment by skattabrain** [comment]
@jleonardolemos Thanks!
